#pragma once

#define EE_HANDS
#define MASTER_RIGHT
#define SPLIT_WATCHDOG_ENABLE
#define SPLIT_WPM_ENABLE
#define ENABLE_COMPILE_KEYCODE
#define PERMISSIVE_HOLD
#define RETRO_TAPPING
#define HOLD_ON_OTHER_KEY_PRESS
#define CHORDAL_HOLD

#define BOOTMAGIC_ROW 0
#define BOOTMAGIC_COLUMN 0
#define BOOTMAGIC_ROW_RIGHT 5
#define BOOTMAGIC_COLUMN_RIGHT 0
